### ISSUE TITLE
브랜드 관련 기능 구현

### ISSUE THREAD

**Issue by imdaxsz** [imdaxsz/orday-front-end#104]
## 📝 개요

브랜드 관련 기능 구현

## ✅ TODO
- [x] 브랜드 리스트 조회 api 응답 바인딩
- [x] 브랜드 상세 조회 api 응답 바인딩
- [x] 관심 브랜드 리스트 조회 api 응답 바인딩
- [x] 관심 브랜드 추가/삭제 구현
