### ISSUE TITLE
카테고리 구조 변경 및 연관된 부분 수정

### ISSUE THREAD

**Issue by imdaxsz** [imdaxsz/orday-front-end#125]
## 📝 개요

카테고리 구조 변경 및 관련 컴포넌트 수정

## ✅ TODO
- [x] 카테고리 타입 및 상수 수정
- [x] 메뉴 수정
- [x] 카테고리 nav 수정
  - [x] 일반 카테고리 
  - [x] 브랜드 상세 페이지  
- [x] 브랜드 상세 조회 응답 타입 수정
