### ISSUE TITLE
장바구니 관련 변경

### ISSUE THREAD

**Issue by lyeejj** [imdaxsz/orday-front-end#171]
## 📝 개요
장바구니 관련된 변경사항 반영

## ✅ TODO
- [x] 장바구니 api 요청 경로 변경
- [x] flex -> grid 스타일 변경
- [x] ProductItem 클릭시 상품 페이지로 이동
- [x] 삭제시 confirm 모달 추가
