### ISSUE TITLE
카테고리 관련 설정 및 수정

### ISSUE THREAD

**Issue by imdaxsz** [imdaxsz/orday-front-end#66]
## 📝 개요

카테고리 관련 설정 및 수정

## ✅ TODO
- [x] 라우터 추가 및 수정
- [x] 헤더 메뉴 드롭다운 수정
   - [x] NEW, BEST, SALE 하위 카테고리 추가
   - [x] 의류 제외한 카테고리 하위 카테고리 제거
- [x] CategoryNav 수정
